name: .NET

on: 
  push:
    paths:
      - 'source/VirtualDesktop/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd source/VirtualDesktop
        dotnet build --no-restore
    
    #There's no tests for now
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
